name: marsrovers
dependencies:
- openssl=1.0.2f=0
- pip=8.0.2=py35_0
- python=3.5.1=0
- readline=6.2=2
- setuptools=19.6.2=py35_0
- sqlite=3.9.2=0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.0.5=0
- zlib=1.2.8=0
- pip:
  - argh==0.26.1
  - args==0.1.0
  - blessings==1.6
  - clint==0.5.1
  - coverage==4.0.3
  - doublex==1.8.2
  - doublex-expects==0.6.0
  - expects==0.7.2
  - mamba==0.8.6
  - mamba-runner==0.0.2
  - mock==1.3.0
  - pathtools==0.1.2
  - pbr==1.8.1
  - pyhamcrest==1.8.5
  - pyyaml==3.11
  - six==1.10.0
  - sure==1.2.24
  - watchdog==0.8.3

